### ISSUE TITLE
"TypeError" When a Label Contains Certain Emails

### ISSUE THREAD

**Issue by jhlee2222** [qoomon/gmail-rss-feed#1]
I'm not sure why, but I'm getting the following error when trying to view some of the feeds generated by the script:

TypeError: Cannot read properties of null (reading 'groups') (line 49, file "Code")

Reproducing the error, I found it seems to happen depending on specific emails being in the feed, though I can't isolate exactly what about these emails causes this. I created a nested label under the label, "RSS", then attempted to view the raw RSS feed that resulted accordingly. It displayed fine, though of course was empty. After moving emails to the label, that's when the feed would no longer display, instead showing the above error.

**Comment by qoomon** [comment]
Thanks for reporting. 
It seems that following regex does not match the sender string see https://github.com/qoomon/gmail-rss-feed/blob/06eba796c744b64fcec5bb858f1d7e3f06d020d4/Code.gs#L49

I'll look into that later

**Comment by qoomon** [comment]
Could you provide me the raw `from:` header of that email?
(just hit the 3-dots next an email and click 'show original' in the plain text you will find the `From: header`)

**Comment by jhlee2222** [comment]
Will this contain the proper heading?

       dkim=pass header.i=@pharmadva.com header.s=c2lr72kqzhuuyhl4b5dqismwxfbz5vup header.b=dndS0ZiY;
       dkim=pass header.i=@amazonses.com header.s=ug7nbtf4gccmlpwj322ax3p6ow6yfsug header.b=kHZCvA2W;
       spf=pass (google.com: domain of 01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com designates 54.240.8.54 as permitted sender) smtp.mailfrom=01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=pharmadva.com
Return-Path: <01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com>
Received: from a8-54.smtp-out.amazonses.com (a8-54.smtp-out.amazonses.com. [54.240.8.54])
        by mx.google.com with ESMTPS id af79cd13be357-7b6d2279e38si383958385a.136.2024.12.09.04.58.44
        for <REDACTED@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Mon, 09 Dec 2024 04:58:45 -0800 (PST)
Received-SPF: pass (google.com: domain of 01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com designates 54.240.8.54 as permitted sender) client-ip=54.240.8.54;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@pharmadva.com header.s=c2lr72kqzhuuyhl4b5dqismwxfbz5vup header.b=dndS0ZiY;
       dkim=pass header.i=@amazonses.com header.s=ug7nbtf4gccmlpwj322ax3p6ow6yfsug header.b=kHZCvA2W;
       spf=pass (google.com: domain of 01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com designates 54.240.8.54 as permitted sender) smtp.mailfrom=01000193ab802dc4-721d3311-9313-4e9e-bbb1-0e458488dbae-000000@amazonses.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=pharmadva.com

If not, let me know. I'm happy to send the original directly to you in full if that helps.

**Comment by qoomon** [comment]
Feel free to try version [`1.0.1`](https://github.com/qoomon/gmail-rss-feed/blob/master/Code.gs)

**Comment by jhlee2222** [comment]
Looks to be working now. Thank you so much!
